# Yellow Jacket Theme

shell = "zsh"

[window]

opacity = 0.9

padding.x = 10

padding.y = 10

decorations = "Full"

decorations_theme_variant = "Dark"

[font]
# Set Font Type
normal = {family = "Hack",style = "Regular"}
bold = {family = "Hack",style = "Bold"}
italic = {family = "Hack",style = "Italic"}
bold_italic = {family = "Hack",style = "Bold Italic"}

# Set Font Offset and Size
glyph_offset = {x = 0, y = 0}
size = 14




# Colors

[colors.cursor]
    
    text = "#77ff00" # Text under cursor
    
    cursor = "#f0d010" # Cursor color
    

[colors.primary] # Primary background and forground colors
    
    foreground = "#cccccc"

    background = "#111516"
    
    dim_foreground = "#666666"
    
    bright_foreground = "#cccccc"
    

[colors.normal] # Normal Colors

    black = "#111516"

    red = "#cc0000"

    green = "#77ff00"

    yellow = "#f0d010"

    blue = "#90bbff"

    magenta = "#cc00ff"

    cyan = "#0fafaf"

    white = "#cccccc"


[colors.bright] # Bright Colors

    black = "#111516"

    red = "#cc0000"

    green = "#77ff00"

    yellow = "#f0d010"

    blue = "#55ffff"

    magenta = "#cc00ff"

    cyan = "#55ffff"

    white = "#cccccc"
    
    
    
    
# Cursor customization
[cursor]
    style= {shape = "Block", blinking = "On"}
    
    blink_interval = 500
